JNK3-MolAIR_A3C:
  Agent:
    type: A3C_RND
    n_steps: 64
    epoch : 6
    seq_len: 35
    seq_mini_batch_size: 16
    padding_value: 0.0
    gamma: 1.0
    gamma_n: 0.99
    lam: 0.95
    nonepi_adv_coef: 1.0
    critic_loss_coef: 0.5
    learning_rate: 0.0007
    grad_norm_clip: 40.0
    rnd_pred_exp_proportion: 0.25
    init_norm_steps: 50
    obs_norm_clip_range: [-5.0, 5.0]
    hidden_state_norm_clip_range: [-5.0, 5.0]
  Env:
    jnk3_coef: 1.0
    init_selfies: ['[C][C][C]', '[C][=C][C]', '[C][C][=N]', '[C][N][C]', '[C][O][C]']
  Train:
    num_envs: 64
    seed: 0
    total_time_steps: 120000
    summary_freq: 1000
    device: cuda
  CountIntReward:
    crwd_coef: 0.01
