QED-SAC:
  Agent:
    type: SAC
    n_steps: 128
    epoch: 6
    seq_len: 35
    seq_mini_batch_size: 16
    gamma: 1.0
    init_alpha: 0.4 
    target_entropy: -6
  Env:
    qed_coef: 1.0
  Train:
    num_envs: 64
    seed: 0
    total_time_steps: 240000
    summary_freq: 1000
    device: cuda
